package:
  name: openff-benchmark
  version: 2021.07.08.0

source:
  git_url: https://github.com/openforcefield/openff-benchmark.git
  git_tag: 2021.07.08.0

build:
  preserve_egg_dir: True
  number: 0 # Build number and string do not work together.
  #string: py{{ py }}_a1 # Alpha version 1.
  skip: True # [win or py27 or py35]
  noarch: python
  script: 
    - ${PYTHON}  -m pip install .

extra:
  #force_upload: True
  upload: benchmark # Upload to anaconda with the "benchmark" label.

requirements:
  build:
    - python
    - setuptools
    # For building sphinx docs
  run:
    - python
    - openforcefield

about:
  home: https://github.com/openforcefield/openff-benchmark
  license: MIT
  license_file: LICENSE
  description: Benchmarking resources for the 2020-2021 Open Force Field partner benchmarking project.
