name: Pure-Python Package Build

on:
  workflow_dispatch:

jobs:
  python-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: sch_tree_installer

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a
      - name: Configure conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.6
          activate-environment: release-build
          environment-file: devtools/conda-envs/release-build.yaml
          auto-activate-base: false

      - name: Environment information
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Build conda package
        shell: bash -l {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.OMNIA_ANACONDA_TOKEN }}
        run: |
          pushd devtools/conda-recipe/
          conda build --token ${ANACONDA_TOKEN} --user omnia --label benchmark-sch --python=3.6 --no-force-upload -c conda-forge -c omnia .
          popd
